language: android
jdk: oraclejdk7
env:
  global:
    - ANDROID_API_LEVEL=android-21
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-21.1.1
  licenses:
    - android-sdk-license-5be876d5 # new license!
    - '.*intel.+'

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_API_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &

# Set execution permission to avoid 'Permission denied' error with gradle 1.8+
  # http://joerglenhard.wordpress.com/2013/10/01/using-travis-ci-with-gradle-wrapper/
  - chmod +x wait_for_emulator

script:
  - ./wait_for_emulator
  - ./gradlew connectedCheck -PdisablePreDex